name: Django CI with Coverage

on:
  push:
    branches:
      - 'feature/**'
      - develop
  pull_request:
    branches:
      - develop
      - main
      - 'feature/**'

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display directory structure for debugging
      run: ls -R
      continue-on-error: true

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install coverage


    - name: Run tests with coverage
      run: |
        coverage erase
        coverage run manage.py test
        coverage report
        coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-html-report
        path: htmlcov  
